### ISSUE TITLE
Scritte in cinese nella barra di ricerca dell'applicazione "Cerca" - 5.11.26 (xiaomi.eu)

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#176]

**Comment by fantakk** [comment]
Facendo uno swipe verso l'alto si accede all'applicazione Cerca. Nella traduzione italiana appaiono scritte in cinese.

![screenshot_2015-11-27-14-11-59_com android quicksearchbox](https://cloud.githubusercontent.com/assets/15057642/11442674/a76ee552-9517-11e5-8df1-128d530b87b9.png)

**Comment by ale8530** [comment]
La nostra versione non ha questo bug.

**Comment by fantakk** [comment]
A chi bisogna segnalarlo quindi scusate?

**Comment by MishFdM** [comment]
Dear user, instead of talk shit about other people's work you download and use for fucking FREE, try to really help doing useful work and show some respect. You say "italian translations really sucks"? Well, don't use it. Have you a fucking idea how many hours everyday this shit costs to me and other translators? You have NO idea. People like you is a cancer for communities, parassites good at nothing, just complain about things you get for FREE and disrespect hard work others do.
And don't fucking report "italian translators won't correct bugs" to anyone, no need for childish behaviour like that. I'm the one you have to talk with when you have issues with MIUI italian translation, so PM me, none else. If someday all this will be shut down, it'll be because of people like you.
